// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA-69oOK9V020-1HI23uB1ba3tHOcce1A',
    appId: '1:931717690308:web:08e2b098c965b64dcc2a91',
    messagingSenderId: '931717690308',
    projectId: 'fooddeliveryapp-18349',
    authDomain: 'fooddeliveryapp-18349.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-18349.firebasestorage.app',
    measurementId: 'G-7Z3VG0S1FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAQu-CtpAO2rQ1qd2ju2m1-BWwdHztAE',
    appId: '1:931717690308:android:fe4cea11591c0858cc2a91',
    messagingSenderId: '931717690308',
    projectId: 'fooddeliveryapp-18349',
    storageBucket: 'fooddeliveryapp-18349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjU2HYDB519-taS6J4NlQXpzmDAI2hmLc',
    appId: '1:931717690308:ios:0cf8a8b63729eb5ccc2a91',
    messagingSenderId: '931717690308',
    projectId: 'fooddeliveryapp-18349',
    storageBucket: 'fooddeliveryapp-18349.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjU2HYDB519-taS6J4NlQXpzmDAI2hmLc',
    appId: '1:931717690308:ios:0cf8a8b63729eb5ccc2a91',
    messagingSenderId: '931717690308',
    projectId: 'fooddeliveryapp-18349',
    storageBucket: 'fooddeliveryapp-18349.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA-69oOK9V020-1HI23uB1ba3tHOcce1A',
    appId: '1:931717690308:web:7d2cfa927f379f50cc2a91',
    messagingSenderId: '931717690308',
    projectId: 'fooddeliveryapp-18349',
    authDomain: 'fooddeliveryapp-18349.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-18349.firebasestorage.app',
    measurementId: 'G-WLJVY9Y9GR',
  );

}