// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWb28nO8WH3jr1UuoKXwdGFzXYSRbsrLQ',
    appId: '1:1031820053214:web:8b80107d75dbdabd3cd04f',
    messagingSenderId: '1031820053214',
    projectId: 'mobileappproject-e6b25',
    authDomain: 'mobileappproject-e6b25.firebaseapp.com',
    storageBucket: 'mobileappproject-e6b25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxUp89uWEM6Dmqwh621q3cZe-by8b50lU',
    appId: '1:1031820053214:android:e623968b91ccd46c3cd04f',
    messagingSenderId: '1031820053214',
    projectId: 'mobileappproject-e6b25',
    storageBucket: 'mobileappproject-e6b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVSd_CqAE0b1Isxk_9eZQaw7X58aqzq3w',
    appId: '1:1031820053214:ios:bae72f4f8d50f0db3cd04f',
    messagingSenderId: '1031820053214',
    projectId: 'mobileappproject-e6b25',
    storageBucket: 'mobileappproject-e6b25.firebasestorage.app',
    iosBundleId: 'com.example.testproject',
  );
}
